<a href="https://colab.research.google.com/github/fahmij8/Metode-Numerik/blob/master/Anum_Dekomposisi_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Komputasi dan Analisis Numerik
### Dekomposisi LU
---
#### Nama : Fahmi Jabbar

##### NIM :1801389

In [0]:
import numpy 
from numpy import *

In [0]:
def jalanLU(A,b):
  n=len(A)

  #========== matriks L dari sini ===================#
  L=zeros((n,n))
  for i in range(0,n):
      L[i][i]=1

  #~~~~~~proses triangularisasi~~~~~~#
  for k in range(0,n-1):                  #-----proses pivot dari sini-------#
      if A[k][k]==0:
          for s in range(0,n):
              v=A[k][s]
              u=A[k+1][s]
              A[k][s]=u
              A[k+1][s]=v
  #-----proses pivot sampai sini-----#
      for j in range(k+1,n):
          m=A[j][k]/A[k][k]
          L[j][k]=m # nilai m disimpan di matriks L
          for i in range(0,n):
              A[j][i]=A[j][i]-m*A[k][i]
  print()
  print('Matriks L')
  print(L)
  #========== matriks L sampai sini =================#

  #========== matriks U dari sini ===================#
  print()
  print('Matriks U')
  print(A)      
  #========== matriks U sampai sini =================#

  #------proses substitusi maju------#
  y=zeros((n,1))
  y[0][0]=b[0][0]/L[0][0]
  for j in range(1,n):
      S=0
      for i in range(0,j):
          S=S+y[i][0]*L[j][i]
      y[j][0]=b[j][0]-S

  #------proses substitusi mundur----#
  x=zeros((n,1))
  x[n-1][0]=y[n-1][0]/A[n-1][n-1]
  for j in range(n-2,-1,-1):
      S=0
      for i in range(j+1,n):
          S=S+A[j][i]*x[i][0]
      x[j][0]=(y[j][0]-S)/A[j][j]
  print()
  print('Solusinya:\n')
  print("X1 = " + str(x[0]) + "\n")
  print("X2 = " + str(x[1]) + "\n")
  print("X3 = " + str(x[2]) + "\n")

## Soal No.1

2x + 4y + 3z = 16

3x + 5y + 2z = 12

4x + 6y + 3z = 12

In [8]:
A = array([[2., 4., 3.],\
           [3., 5., 2.],\
           [4., 6., 3.]])
print('Matriks A')
print (A)

b = array([[16.],\
           [12.],\
           [12.]])
print('')
print('Matriks B')
print(b)
jalanLU(A,b)

Matriks A
[[2. 4. 3.]
 [3. 5. 2.]
 [4. 6. 3.]]

Matriks B
[[16.]
 [12.]
 [12.]]

Matriks L
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [2.  2.  1. ]]

Matriks U
[[ 2.   4.   3. ]
 [ 0.  -1.  -2.5]
 [ 0.   0.   2. ]]

Solusinya:

X1 = [-9.]

X2 = [7.]

X3 = [2.]



## Soal No.2

x + y - z = 4

x - 2y + 3z = -6

2x + 3y + z = 7

In [9]:
A = array([[1., 1., -1.],\
           [1., -2., 3.],\
           [2., 3., 1.]])
print('Matriks A')
print (A)

b = array([[4.],\
           [-6.],\
           [7.]])
print('')
print('Matriks B')
print(b)
jalanLU(A,b)

Matriks A
[[ 1.  1. -1.]
 [ 1. -2.  3.]
 [ 2.  3.  1.]]

Matriks B
[[ 4.]
 [-6.]
 [ 7.]]

Matriks L
[[ 1.          0.          0.        ]
 [ 1.          1.          0.        ]
 [ 2.         -0.33333333  1.        ]]

Matriks U
[[ 1.          1.         -1.        ]
 [ 0.         -3.          4.        ]
 [ 0.          0.          4.33333333]]

Solusinya:

X1 = [1.]

X2 = [2.]

X3 = [-1.]

